// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using levihobbs.Data;

#nullable disable

namespace levihobbs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250709035155_AddToneModel")]
    partial class AddToneModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookReviewBookshelf", b =>
                {
                    b.Property<int>("BookReviewsId")
                        .HasColumnType("integer");

                    b.Property<int>("BookshelvesId")
                        .HasColumnType("integer");

                    b.HasKey("BookReviewsId", "BookshelvesId");

                    b.HasIndex("BookshelvesId");

                    b.ToTable("BookReviewBookshelves", (string)null);
                });

            modelBuilder.Entity("BookshelfBookshelfGrouping", b =>
                {
                    b.Property<int>("BookshelfGroupingsId")
                        .HasColumnType("integer");

                    b.Property<int>("BookshelvesId")
                        .HasColumnType("integer");

                    b.HasKey("BookshelfGroupingsId", "BookshelvesId");

                    b.HasIndex("BookshelvesId");

                    b.ToTable("BookshelfGroupingBookshelves", (string)null);
                });

            modelBuilder.Entity("levihobbs.Models.BookCoverImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDownloaded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BookCoverImages");
                });

            modelBuilder.Entity("levihobbs.Models.BookReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int?>("CoverImageId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateRead")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasReviewContent")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("boolean")
                        .HasComputedColumnSql("CASE WHEN \"MyReview\" IS NOT NULL AND \"MyReview\" != '' THEN true ELSE false END", true);

                    b.Property<int>("MyRating")
                        .HasColumnType("integer");

                    b.Property<string>("MyReview")
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfPages")
                        .HasColumnType("integer");

                    b.Property<int?>("OriginalPublicationYear")
                        .HasColumnType("integer");

                    b.Property<string>("SearchableString")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoverImageId");

                    b.HasIndex("HasReviewContent")
                        .HasDatabaseName("IX_BookReview_HasReviewContent")
                        .HasFilter("\"HasReviewContent\" = true");

                    b.HasIndex("SearchableString")
                        .HasDatabaseName("IX_BookReview_SearchableString");

                    b.ToTable("BookReviews", t =>
                        {
                            t.HasCheckConstraint("CK_BookReview_AverageRating", "\"AverageRating\" BETWEEN 0 AND 5");

                            t.HasCheckConstraint("CK_BookReview_MyRating", "\"MyRating\" BETWEEN 0 AND 5");
                        });
                });

            modelBuilder.Entity("levihobbs.Models.Bookshelf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Display")
                        .HasColumnType("boolean");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Bookshelves");
                });

            modelBuilder.Entity("levihobbs.Models.BookshelfGrouping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BookshelfGroupings");
                });

            modelBuilder.Entity("levihobbs.Models.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("levihobbs.Models.NewsletterSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("SubscriptionDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NewsletterSubscriptions");
                });

            modelBuilder.Entity("levihobbs.Models.Tone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Tones");
                });

            modelBuilder.Entity("BookReviewBookshelf", b =>
                {
                    b.HasOne("levihobbs.Models.BookReview", null)
                        .WithMany()
                        .HasForeignKey("BookReviewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("levihobbs.Models.Bookshelf", null)
                        .WithMany()
                        .HasForeignKey("BookshelvesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookshelfBookshelfGrouping", b =>
                {
                    b.HasOne("levihobbs.Models.BookshelfGrouping", null)
                        .WithMany()
                        .HasForeignKey("BookshelfGroupingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("levihobbs.Models.Bookshelf", null)
                        .WithMany()
                        .HasForeignKey("BookshelvesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("levihobbs.Models.BookReview", b =>
                {
                    b.HasOne("levihobbs.Models.BookCoverImage", "CoverImage")
                        .WithMany()
                        .HasForeignKey("CoverImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CoverImage");
                });

            modelBuilder.Entity("levihobbs.Models.Tone", b =>
                {
                    b.HasOne("levihobbs.Models.Tone", "Parent")
                        .WithMany("Subtones")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("levihobbs.Models.Tone", b =>
                {
                    b.Navigation("Subtones");
                });
#pragma warning restore 612, 618
        }
    }
}
